name: Trigger - Lease Tracker Deploy
on:
  workflow_dispatch:
    inputs:
      ref:
        default: expo
        description: ref of lease-tracker repo
        type: string
jobs:
  deploy:
    strategy:
      matrix:
        platform:
          - ios
          - android
    runs-on: ${{ matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest'}}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: qwezey/lease-tracker
          ref: ${{ inputs.ref }}
          token: ${{ secrets.QWEZEY_BOT_TOKEN }}
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - run: npm run prod-build-${{ matrix.platform }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
