name: Trigger - Lease Tracker Deploy
on:
  workflow_dispatch:
    inputs:
      ref:
        default: expo
        description: ref of lease-tracker repo
        type: string
jobs:
  deploy:
    strategy:
      matrix:
        platform:
          - ios
          - android
    env:
      BUILD_PATH: build.${{ matrix.platform == 'ios' && 'ipa' || 'aab'}}
    runs-on: ${{ matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest'}}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: qwezey/lease-tracker
          ref: ${{ inputs.ref }}
          token: ${{ secrets.QWEZEY_BOT_TOKEN }}
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.platform == 'ios' }}
        with:
          xcode-version: latest-stable
      - run: xcodebuild -downloadPlatform iOS
        if: ${{ matrix.platform == 'ios' }}
      - run: npm ci
      - run: npm run build -- --non-interactive --platform ${{ matrix.platform }} --output ${{ env.BUILD_PATH }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
      - run: npm run eas -- submit --non-interactive --platform ${{ matrix.platform }} --path ${{ env.BUILD_PATH }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
